# -*- coding: utf-8 -*-
"""
KPSS Tarih Modülü Üreticisi (18 Ünite, 54 Ders, 540 Soru)
"""
import sys
from common import (
    make_concept_card, make_mc, make_tf, make_fib, make_match,
    make_lesson, make_unit, esc
)

tarih_units_meta = [
    (1, "İslamiyet Öncesi Türk Tarihi & Kültür Medeniyet", [
        ("İlk Türk Devletleri ve Siyasi Olaylar", "Asya Hun, I. ve II. Göktürk, Uygurlar ve Boylar",
         "İslamiyet Öncesi Temel Kavramlar",
         "- Kut: Devleti yönetme yetkisinin Tanrı tarafından verildiğine inanılması (Veraset sistemini ve taht kavgalarını doğurmuştur).\n- Kurultay (Toy/Kengeş): Devlet işlerinin görüşüldüğü meclis.\n- İkili Teşkilat: Doğu (Hakan) ve Batı (Yabgu).\n- Uygurlar: Maniheizm etkisiyle yerleşik hayata geçen ilk Türk devletidir.",
         "Kut kan bağıyla babadan oğula geçtiği için Türk devletlerinin kısa sürede parçalanıp yıkılmasının en temel sebebidir!", "🏹",
         [("mc", "Tarihte Türk adıyla kurulan ilk devlet ve kendi milli alfabesini kullanan ilk Türk topluluğu hangisidir?",
           ["Göktürkler (Kök Türkler)", "Hunlar", "Uygurlar", "Karahanlılar", "Avarlar"], 0, "Bumin Kağan tarafından kurulan Göktürkler Türk adını resmi devlet adı olarak kullanmıştır."),
          ("mc", "Türk tarihinde ilk kez yerleşik hayata geçen, tapınaklar inşa eden ve matbaayı kullanan devlet hangisidir?",
           ["Uygurlar", "Asya Hun Devleti", "I. Göktürk Devleti", "Avarlar", "Hazarlar"], 0, "Bögü Kağan döneminde Maniheizmi kabul eden Uygurlar yerleşik hayata geçen ilk Türk devletidir."),
          ("mc", "Bizans ordusunda ücretli askerlik yaparken 1071 Malazgirt Savaşı'nda Selçuklu saflarına geçen Türk boyları hangileridir?",
           ["Peçenekler - Uzlar", "Hazarlar - Bulgarlar", "Avarlar - Macarlar", "Kıpçaklar - Kırgızlar", "Türgişler - Karluklar"], 0, "Peçenekler ve Uzlar Malazgirt Savaşı'nda taraf değiştirerek zaferde kritik rol oynamıştır."),
          ("mc", "Musevilik dinini benimseyen ilk ve tek Türk devleti aşağıdakilerden hangisidir?",
           ["Hazarlar", "Avarlar", "Uygurlar", "Kimekler", "Macarlar"], 0, "Hazarlar Museviliği kabul etmiş ve Kafkaslarda İslamiyet'in yayılmasını bir süre engellemiştir."),
          ("mc", "Mete Han tarafından kurulan ve Türk Kara Kuvvetleri'nin kuruluş tarihi kabul edilen askeri sistem hangisidir?",
           ["Onlu Teşkilat (MÖ 209)", "Tımar Sistemi", "Gulam Sistemi", "İkili Teşkilat", "Kurultay"], 0, "Mete Han MÖ 209'da onlu teşkilatı kurarak düzenli ordunun temelini atmıştır."),
          ("mc", "Avrupa Hun Devleti hükümdarı Attila'ya Avrupalılar tarafından hangi unvan verilmiştir?",
           ["Tanrının Kırbacı (Flagellum Dei)", "Cesur Kral", "Güneşin Oğlu", "Büyük Kağan", "Yabgu"], 0, "Attila Hristiyan dünyasını cezalandırmak için gönderildiğine inanıldığı için Tanrının Kırbacı unvanını almıştır."),
          ("tf", "İslamiyet öncesi Türk devletlerinde göçebe yaşam tarzı nedeniyle uzun süreli hapis cezaları yaygın uygulanmıştır.",
           False, "Göçebe yaşam nedeniyle hapis cezaları en fazla 10 gün civarında ve kısa süreli olmuştur."),
          ("fib", "İslamiyet öncesi Türklerde hükümdarın olmadığı zamanlarda kurultaya başkanlık eden vezire ... denirdi.",
           ["Aygucı", "Tudun", "Buyruk", "Tigin"], "Aygucı", "Aygucı veya Üge başbakan niteliğindeki vezirdir."),
          ("match", "Kavramları eşleştiriniz:",
           [("Kurgan", "Mezar"), ("Balbal", "Mezar taşı"), ("Yuğ", "Cenaze töreni"), ("Sagu", "Ağıt")], "Türk mezar ve yas kültürü kavramlarıdır.")]),
        ("Kültür, Medeniyet ve Töre", "Kut, Kurultay, Veraset, Hukuk ve Toplumsal Hayat",
         "İslamiyet Öncesi Sosyal Yapı ve Hukuk",
         "- Oguş (Aile) -> Urug (Sülale) -> Boy (Kabile) -> Bodun (Millet) -> İl (Devlet).\n- Töre: Yazısız hukuk kurallarıdır, hakan dahil herkes uymak zorundadır.\n- Toprak mülkiyeti devlete aittir; feodalite ve köle sınıfı oluşmamıştır.",
         "ÖSYM Tuzağı: Türklerde özel mülkiyetin olmaması sınıfsız, eşitlikçi bir toplum yapısı sağlamıştır!", "⚖️",
         [("mc", "İslamiyet öncesi Türk toplumunda sosyal yapının en küçük basamağından en büyüğüne doğru sıralanışı hangisidir?",
           ["Oguş - Urug - Boy - Bodun - İl", "Urug - Oguş - Boy - İl - Bodun", "Boy - Bodun - İl - Oguş - Urug", "Oguş - Boy - Urug - İl - Bodun", "İl - Bodun - Boy - Urug - Oguş"], 0, "Oguş (aile), Urug (sülale), Boy (kabile), Bodun (millet), İl (devlettir)."),
          ("mc", "Aşağıdakilerden hangisi İslamiyet öncesi Türk hükümdarlık alametlerinden biri DEĞİLDİR?",
           ["Hutbe okutmak", "Otağ (Hükümdar çadırı)", "Örgin (Taht)", "Tuğ (Sancak)", "Kotuz (Sorguç)"], 0, "Hutbe okutmak İslami bir hükümdarlık sembolüdür; İslamiyet öncesinde yoktur."),
          ("mc", "Türklerde cenaze törenlerine ne ad verilirdi?",
           ["Yuğ", "Kurgan", "Tamu", "Uçmağ", "Balbal"], 0, "Yuğ cenaze merasiminin adıdır."),
          ("mc", "Tarihte bilinen ilk Türk şairi aşağıdakilerden hangisidir?",
           ["Aprınçur Tigin", "Kaşgarlı Mahmut", "Yusuf Has Hacip", "Vezir Tonyukuk", "Bilge Kağan"], 0, "Uygurlar döneminde yaşayan Aprınçur Tigin ilk Türk şairi kabul edilir."),
          ("mc", "Törede hiçbir zaman değiştirilemeyen 4 temel adalet ve ahlak ilkesi arasında hangisi yer almaz?",
           ["Mutlak Monarşi", "Könilik (Adalet)", "Uzluk (İyilik/Faydalılık)", "Tüzlük (Eşitlik)", "İnsanlık (Kişilik)"], 0, "Törenin 4 değişmez ilkesi Könilik, Uzluk, Tüzlük ve İnsanlıktır."),
          ("mc", "Kendi adına madeni para (Yarmak) bastıran ilk Türk hükümdarı kimdir?",
           ["Baga Tarkan (Türgişler)", "Bumin Kağan", "Mete Han", "Attila", "Kutluk Kağan"], 0, "Baga Tarkan kendi adına madeni para bastıran ilk Türk kağanıdır."),
          ("tf", "Uygurlar matbaayı ve hareketli harf sistemini kullanan ilk Türk devletidir.",
           True, "Uygurlar Çinlilerden öğrendikleri matbaa ve kağıdı geliştirerek kitap basmışlardır."),
          ("fib", "İslamiyet öncesi Türklerde cennet kavramına ... denirdi.",
           ["Uçmağ", "Tamu", "Kurgan", "Kam"], "Uçmağ", "Uçmağ cennet, Tamu cehennemdir."),
          ("match", "Destanları boylarla eşleştiriniz:",
           [("Ergenekon", "Göktürkler"), ("Göç", "Uygurlar"), ("Oğuz Kağan", "Asya Hun"), ("Manas", "Kırgızlar")], "Türk destanları ve ait oldukları boylardır.")]),
        ("İslamiyet Öncesi Türk Tarihi Kupa Sınavı 🏆", "Tüm İslamiyet Öncesi Konularını Kapsayan Kupa Denemesi",
         "İslamiyet Öncesi Sınav Püf Noktaları",
         "- Orhun Abideleri: Türk tarihinin ve edebiyatının ilk yazılı belgeleridir (II. Göktürk).\n- İlk vezir ve tarihçi: Vezir Tonyukuk (Apa Tarkan).\n- Moğollara itaat eden ilk Türk devleti: Kırgızlar (Müslüman olarak Karluklar).",
         "Sınavda hükümdarlık sembolü olarak 'Para bastırmak', 'Hilat', 'Tıraz' ve 'Menşur' İslamiyet ile gelmiştir, İslamiyet öncesinde yoktur!", "🏆",
         [("mc", "Orhun Abideleri hangi devlet döneminde dikilmiştir?",
           ["II. Göktürk (Kutluk) Devleti", "I. Göktürk Devleti", "Asya Hun Devleti", "Uygurlar", "Karahanlılar"], 0, "Orhun Abideleri II. Göktürk döneminde Bilge Kağan, Kültigin ve Tonyukuk adına dikilmiştir."),
          ("mc", "Türk tarihinin ilk veziri, ilk yazarı ve Türklerin 'Bismark'ı olarak anılan devlet adamı kimdir?",
           ["Vezir Tonyukuk", "Bumin Kağan", "İlteriş Kağan", "Bögü Kağan", "Mukan Kağan"], 0, "Vezir Tonyukuk kendi anıtını dikerek tarihteki ilk Türk anı yazarı olmuştur."),
          ("mc", "İstanbul'u tarihte ilk kuşatan Türk devleti hangisidir?",
           ["Avarlar", "Hazarlar", "Hunlar", "Peçenekler", "Bulgarlar"], 0, "Avarlar Sasanilerle iş birliği yaparak İstanbul'u kuşatan ilk Türk devletidir."),
          ("mc", "Dünyanın en uzun destanı olan 'Manas Destanı' hangi Türk boyuna aittir?",
           ["Kırgızlar", "Kazaklar", "Özbekler", "Uygurlar", "Kıpçaklar"], 0, "Manas Destanı Kırgızlara aittir ve canlı bir destandır."),
          ("mc", "İslamiyet öncesi Türklerde hükümdarın erkek çocuklarına ne ad verilirdi?",
           ["Tigin", "Şad", "Ataman", "İnanç", "Tarkan"], 0, "Hükümdar çocuklarına Tigin, onların eğitmenine ise Ataman/İnal denirdi."),
          ("mc", "Orhun Abideleri'ni Danimarkalı dilbilimci Vilhelm Thomsen çözerken okuduğu ilk kelime hangisidir?",
           ["Tengri (Tanrı)", "Türk", "Kül Tigin", "Kağan", "Orhun"], 0, "Thomsen yazıtlarda ilk olarak 'Tengri' kelimesini çözmüştür."),
          ("tf", "Hazarlar İslam ordularıyla (Hz. Osman dönemi Belencer Savaşı) savaşarak Kafkasların İslamlaşmasını geciktirmiştir.",
           True, "Hazarlar Belencer Savaşı'nda İslam ordularını durdurmuştur."),
          ("fib", "İslamiyet öncesinde savaşlarda cesaret gösteren yiğitlere takılan unvana ... denir.",
           ["Alp", "Tudun", "Yabgu", "Tigin"], "Alp", "Cesur savaşçılara Alp veya Tarkan unvanı verilirdi."),
          ("match", "Kavramları görevleri ile eşleştiriniz:",
           [("Tudun", "Vergi memuru"), ("Tutuk", "Askeri vali"), ("Buyruk", "Bakan"), ("Yargıcı", "Yargıç")], "İslamiyet öncesi bürokrasi görevlileridir.")])
    ]),
    (2, "İlk Müslüman Türk Devletleri & Türk-İslam Medeniyeti", [
        ("Karahanlı, Gazneli ve Büyük Selçuklu", "Talas Savaşı, Devletlerin Kuruluşu ve Siyasi Olaylar",
         "İlk Türk-İslam Devletleri Özeti",
         "- Talas Savaşı (751): Karluklar Abbasilere yardım etti, İslamlaşma başladı, kağıt Çin dışına çıktı.\n- Karahanlılar: Orta Asya'da kurulan ilk Müslüman Türk devleti. Satuk Buğra Han İslamiyeti kabul etti.\n- Gazneliler: Gazneli Mahmut Sultan unvanını kullanan ilk Türk hükümdarıdır.\n- Büyük Selçuklu: 1040 Dandanakan ile kuruldu, 1071 Malazgirt ile Anadolu'nun kapıları açıldı.",
         "Karahanlılar milli kimliğini en güçlü koruyan devlettir (Resmi dil Türkçe). Gazneli ve Selçuklu'da Farsça ve Arapça ağırlıktadır!", "🕌",
         [("mc", "Tarihte 'Sultan' unvanını kullanan ilk Türk hükümdarı kimdir?",
           ["Gazneli Mahmut", "Tuğrul Bey", "Alparslan", "Melikşah", "Satuk Buğra Han"], 0, "Abbaso Halifesi Şii Büveyhoğulları tehlikesine karşı koruduğu için Gazneli Mahmut'a Sultan unvanını vermiştir."),
          ("mc", "Büyük Selçuklu Devleti'nin resmen kurulmasını sağlayan ve Gaznelileri yıkılış sürecine sokan 1040 tarihli savaş hangisidir?",
           ["Dandanakan Savaşı", "Pasinler Savaşı", "Malazgirt Savaşı", "Katvan Savaşı", "Yassıçemen Savaşı"], 0, "1040 Dandanakan Savaşı ile Büyük Selçuklu resmen kurulmuştur."),
          ("mc", "1071 Malazgirt Zaferi'nden sonra Abbasi Halifesi Sultan Alparslan'a hangi unvanı vermiştir?",
           ["Ebu'l Feth (Fetihlerin Babası)", "Sultanu'l Azam", "Şah-ı Cihan", "Sultan-ı İklim-i Rum", "Hüccetü'l İslam"], 0, "Sultan Alparslan Ani Kalesi ve Malazgirt zaferleri nedeniyle Ebu'l Feth unvanını almıştır."),
          ("mc", "Mısır'da kurulan ve kutsal topraklara (Hicaz) egemen olan ilk Türk-İslam devleti hangisidir?",
           ["İhşidiler (Akşitler)", "Tolunoğulları", "Eyyubiler", "Memlükler", "Osmanlılar"], 0, "İhşidiler Mekke ve Medine'ye hakim olan ilk Türk devletidir."),
          ("mc", "1187 Hıttin Savaşı ile Kudüs'ü Haçlılardan geri alarak III. Haçlı Seferi'ne yol açan lider kimdir?",
           ["Selahaddin Eyyubi", "Sultan Baybars", "Nurettin Zengi", "Alparslan", "Kılıç Arslan"], 0, "Selahaddin Eyyubi Kudüs Fatihi olarak tarihe geçmiştir."),
          ("mc", "Moğolları tarihte ilk kez 1260 Ayn Calut Savaşı'nda mağlup eden Türk devleti hangisidir?",
           ["Memlükler", "Büyük Selçuklu", "Eyyubiler", "Harzemşahlar", "Altın Orda"], 0, "Memlük hükümdarı Sultan Baybars Moğolları Ayn Calut'ta durdurmuştur."),
          ("tf", "Talas Savaşı'ndan sonra kağıt Çin dışında ilk kez Semerkant şehrinde üretilmiştir.",
           True, "Semerkant kağıt üretim merkezi olmuş ve Şehirlerin Şahı unvanını almıştır."),
          ("fib", "Büyük Selçuklu Devleti'nde Hasan Sabbah'ın kurduğu ... tarikatı devleti içten çökertmeye çalışmıştır.",
           ["Batinilik (Haşhaşiler)", "Babailik", "Hurufilik", "Bektaşilik"], "Batinilik (Haşhaşiler)", "Batinilik Selçuklu devlet adamlarına suikastlar düzenlemiştir."),
          ("match", "Şehir unvanlarını eşleştiriniz:",
           [("Buhara", "İslam'ın Roması"), ("Semerkant", "Şehirlerin Şahı"), ("İsfahan", "Nısf-ı Cihan"), ("Kaşgar", "Işıldayan İnci")], "Tarihi Türk-İslam şehirleri ve unvanlarıdır.")]),
        ("İlk Türk-İslam Edebi Eserleri ve Bilginleri", "Kutadgu Bilig, Divanü Lugati't-Türk, Farabi ve İbn-i Sina",
         "İlk Edebi Eserler Tablosu",
         "- Kutadgu Bilig (Yusuf Has Hacip): İlk Türk-İslam eseri, siyasetnamedir.\n- Divanü Lugati't-Türk (Kaşgarlı Mahmut): İlk Türkçe sözlük ve ilk Türk dünyası haritası.\n- Atabetü'l-Hakayık (Edip Ahmet Yükneki): Hakikatlerin eşiği, ahlak kitabıdır.\n- Divan-ı Hikmet (Ahmet Yesevi): İlk tasavvuf eseridir.",
         "ÖSYM bu 4 eserin yazarlarını, içeriklerini ve sunuldukları devlet adamlarını düzenli olarak sormaktadır!", "📚",
         [("mc", "Türk tarihinin ilk siyasetnamesi kabul edilen ve mutluluk veren bilgi anlamına gelen eser hangisidir?",
           ["Kutadgu Bilig", "Divanü Lugati't-Türk", "Siyasetname", "Atabetü'l-Hakayık", "Divan-ı Hikmet"], 0, "Yusuf Has Hacip tarafından yazılan Kutadgu Bilig ilk siyasetnamedir."),
          ("mc", "Araplara Türkçeyi öğretmek amacıyla yazılan ilk Türkçe ansiklopedik sözlük kime aittir?",
           ["Kaşgarlı Mahmut", "Yusuf Has Hacip", "Ali Şir Nevai", "Edip Ahmet Yükneki", "Hoca Ahmet Yesevi"], 0, "Kaşgarlı Mahmut Divanü Lugati't-Türk eserinin yazarıdır."),
          ("mc", "Batıda 'Avicenna' olarak tanınan ve 'El-Kanun fi't-Tıbb' kitabının yazarı olan İslam bilgini kimdir?",
           ["İbn-i Sina", "Farabi", "Biruni", "Razi", "İbn-i Rüşd"], 0, "İbn-i Sina tıp alanındaki çalışmalarıyla Batıda Avicenna olarak bilinir."),
          ("mc", "Aristo'dan sonra felsefe alanındaki derin bilgisi sebebiyle 'Muallim-i Sani' (İkinci Öğretmen) unvanını alan düşünür kimdir?",
           ["Farabi", "İbn-i Sina", "Gazali", "Harezmi", "Biruni"], 0, "Farabi Muallim-i Sani unvanlı büyük Türk-İslam filozofudur."),
          ("mc", "Sıfır (0) rakamını ilk kez matematiğe kazandıran ve cebir ilminin kurucusu kabul edilen bilgin kimdir?",
           ["Harezmi", "Ömer Hayyam", "Ali Kuşçu", "Biruni", "Nasirüddin Tusi"], 0, "Harezmi 'El-Cebr ve'l-Mukabele' eseriyle cebrin kurucusudur."),
          ("mc", "Gazneli Mahmut'un 'Sarayımın en değerli hazinesidir' dediği astronom ve matematik bilgini kimdir?",
           ["Biruni", "Farabi", "İbn-i Heysem", "Uluğ Bey", "Ali Şir Nevai"], 0, "Biruni dünyanın yarıçapını ve eksen eğikliğini hesaplamıştır."),
          ("tf", "Nizamiye Medreseleri Vezir Nizamülmülk tarafından Bağdat'ta kurulan ilk üniversite düzeyindeki kurumlardır.",
           True, "Nizamiye Medreseleri Batinilik tehlikesine karşı ilmi savunma amacıyla açılmıştır."),
          ("fib", "Tasavvuf felsefesinin temeli sayılan Divan-ı Hikmet adlı eserin yazarı ...'dir.",
           ["Hoca Ahmet Yesevi", "Yunus Emre", "Mevlana", "Hacı Bektaş Veli"], "Hoca Ahmet Yesevi", "Ahmet Yesevi Pir-i Türkistan olarak anılır."),
          ("match", "Eserleri yazarlarıyla eşleştiriniz:",
           [("Kutadgu Bilig", "Yusuf Has Hacip"), ("Divanu Lugati't-Türk", "Kaşgarlı Mahmut"), ("Atabetü'l-Hakayık", "Edip Ahmet Yükneki"), ("Divan-ı Hikmet", "Ahmet Yesevi")], "Temel Türk-İslam klasikleridir.")]),
        ("İlk Türk-İslam Devletleri Kupa Sınavı 🏆", "Devlet Yönetimi, İkta Sistemi ve Sınav Denemesi",
         "Türk-İslam Devlet Teşkilatı",
         "- İkta Sistemi: Toprak gelirlerinin askeri hizmet karşılığı tahsis edilmesidir. Hazineye yük olmadan ordu yetiştirir.\n- Gulam Sistemi: Devşirme çocukların asker ve yönetici olarak eğitilmesidir.\n- Ribat: Kervansaray ve sınır güvenliği yapılarıdır.\n- Muhtesip: Çarşı ve pazar denetçisi zabıtadır.",
         "İkta sistemi taşrada üretimin sürekliliğini, asayişi ve bedava süvari ordusu yetiştirilmesini sağlar!", "🏆",
         [("mc", "Büyük Selçuklu Devleti'nde Sultan Alparslan ve Melikşah'a vezirlik yapan, Siyasetname'yi yazan devlet adamı kimdir?",
           ["Nizamülmülk", "Ali Şir Nevai", "Sadrettin Konevi", "Köprülü Mehmet", "Kemalettin İsmail"], 0, "Nizamülmülk Nizamiye Medreseleri ve Siyasetname ile tanınır."),
          ("mc", "Güneş yılı esaslı Celali Takvimi'ni Sultan Melikşah adına hazırlayan ünlü bilgin ve şair kimdir?",
           ["Ömer Hayyam", "Ali Kuşçu", "Uluğ Bey", "Harezmi", "Nasirüddin Tusi"], 0, "Ömer Hayyam Celali Takvimi'ni hazırlamış ve Rubaileriyle ün kazanmıştır."),
          ("mc", "Türk-İslam devletlerinde çarşı, pazar ve esnafı denetleyen görevli hangisidir?",
           ["Muhtesip", "Hacib", "Emir-i Dad", "Subaşı", "Kadı"], 0, "Muhtesip piyasa denetimi ve zabıta işlerine bakar."),
          ("mc", "Memlük Devleti'nde diğer Türk devletlerinden farklı olarak veraset sisteminde hangi kural geçerliydi?",
           ["Her güçlü emirin sultan olabilme hakkı vardı", "Kut sadece padişahın büyük oğluna geçerdi", "Hükümdarı halk seçerdi", "Kadınlar da hükümdar olabilirdi", "Yabancı prensler tahta çıkabilirdi"], 0, "Memlüklerde komutanlar tahta geçebildiği için sık sık taht değişikliği yaşanmıştır."),
          ("mc", "İlk Türk-İslam devletlerinde kervansaray niteliği taşıyan ilk yapılara ne ad verilirdi?",
           ["Ribat", "Kümbet", "Külliye", "İmaret", "Tekke"], 0, "Karahanlılar döneminde inşa edilen Ribatlar kervansarayların öncüsüdür."),
          ("mc", "Aşağıdakilerden hangisi Büyük Selçuklu Devleti'nin yıkılmasıyla ortaya çıkan Atabeyliklerden biri DEĞİLDİR?",
           ["Danişmentliler", "Zengiler", "Böriler", "İldenizoğulları", "Salgurlular"], 0, "Danişmentliler Malazgirt sonrası Anadolu'da kurulan I. Beyliklerdendir."),
          ("tf", "İkta sahipleri aldıkları vergilerin bir kısmıyla 'Cebelü' adı verilen atlı asker beslemek zorundaydı.",
           True, "İkta sistemi Selçuklu ordusunun omurgasını oluşturan Cebelü süvarilerini yetiştirirdi."),
          ("fib", "Türk-İslam devletlerinde adaletten sorumlu şeri davalara bakan hakimlere ... denirdi.",
           ["Kadı", "Subaşı", "Muhtesip", "Amit"], "Kadı", "Kadılar şeri hukuku uygular, başlarındaki görevliye Kadıü'l Kudat denirdi."),
          ("match", "Kavramları eşleştiriniz:",
           [("İkta", "Toprak gelirli askerlik"), ("Gulam", "Saray köle askerleri"), ("Ribat", "Kervansaray"), ("Hacib", "Hükümdar başdanışmanı")], "Türk-İslam idari kurumlarıdır.")])
    ])
]

print("Tarih modulu metadata hazir.")
